import 'package:phone_numbers_parser/phone_numbers_parser.dart';

/// A country/territory the phone-number field lets the user pick as the
/// country code for their number.
class Country {
  final IsoCode isoCode;
  final String name;

  const Country(this.isoCode, this.name);

  /// The dial code that precedes the national number (e.g. "1" for the US),
  /// from `phone_numbers_parser`'s own numbering-plan data — never hand-typed,
  /// so it can't drift out of sync with what actually validates.
  String get dialCode => PhoneNumber(isoCode: isoCode, nsn: '').countryCode;

  /// The flag, built from Unicode regional indicator symbols rather than an
  /// image asset, so it needs no bundled artwork and is always correct.
  String get flag {
    const base = 0x1F1E6;
    const aCode = 0x41; // 'A'
    return String.fromCharCodes(
      isoCode.name.codeUnits.map((c) => base + (c - aCode)),
    );
  }
}

/// Every country/territory offered in the picker, alphabetical by name. Names
/// are the standard short English country/territory names (ISO 3166-1); the
/// dial codes and validation rules come entirely from `phone_numbers_parser`.
final List<Country> kCountries = List<Country>.of(_kCountries)
  ..sort((a, b) => a.name.compareTo(b.name));

const List<Country> _kCountries = [
  Country(IsoCode.AC, 'Ascension Island'),
  Country(IsoCode.AD, 'Andorra'),
  Country(IsoCode.AE, 'United Arab Emirates'),
  Country(IsoCode.AF, 'Afghanistan'),
  Country(IsoCode.AG, 'Antigua and Barbuda'),
  Country(IsoCode.AI, 'Anguilla'),
  Country(IsoCode.AL, 'Albania'),
  Country(IsoCode.AM, 'Armenia'),
  Country(IsoCode.AO, 'Angola'),
  Country(IsoCode.AR, 'Argentina'),
  Country(IsoCode.AS, 'American Samoa'),
  Country(IsoCode.AT, 'Austria'),
  Country(IsoCode.AU, 'Australia'),
  Country(IsoCode.AW, 'Aruba'),
  Country(IsoCode.AX, 'Åland Islands'),
  Country(IsoCode.AZ, 'Azerbaijan'),
  Country(IsoCode.BA, 'Bosnia and Herzegovina'),
  Country(IsoCode.BB, 'Barbados'),
  Country(IsoCode.BD, 'Bangladesh'),
  Country(IsoCode.BE, 'Belgium'),
  Country(IsoCode.BF, 'Burkina Faso'),
  Country(IsoCode.BG, 'Bulgaria'),
  Country(IsoCode.BH, 'Bahrain'),
  Country(IsoCode.BI, 'Burundi'),
  Country(IsoCode.BJ, 'Benin'),
  Country(IsoCode.BL, 'Saint Barthélemy'),
  Country(IsoCode.BM, 'Bermuda'),
  Country(IsoCode.BN, 'Brunei'),
  Country(IsoCode.BO, 'Bolivia'),
  Country(IsoCode.BQ, 'Caribbean Netherlands'),
  Country(IsoCode.BR, 'Brazil'),
  Country(IsoCode.BS, 'Bahamas'),
  Country(IsoCode.BT, 'Bhutan'),
  Country(IsoCode.BW, 'Botswana'),
  Country(IsoCode.BY, 'Belarus'),
  Country(IsoCode.BZ, 'Belize'),
  Country(IsoCode.CA, 'Canada'),
  Country(IsoCode.CC, 'Cocos (Keeling) Islands'),
  Country(IsoCode.CD, 'DR Congo'),
  Country(IsoCode.CF, 'Central African Republic'),
  Country(IsoCode.CG, 'Republic of the Congo'),
  Country(IsoCode.CH, 'Switzerland'),
  Country(IsoCode.CI, 'Côte d\'Ivoire'),
  Country(IsoCode.CK, 'Cook Islands'),
  Country(IsoCode.CL, 'Chile'),
  Country(IsoCode.CM, 'Cameroon'),
  Country(IsoCode.CN, 'China'),
  Country(IsoCode.CO, 'Colombia'),
  Country(IsoCode.CR, 'Costa Rica'),
  Country(IsoCode.CU, 'Cuba'),
  Country(IsoCode.CV, 'Cape Verde'),
  Country(IsoCode.CW, 'Curaçao'),
  Country(IsoCode.CX, 'Christmas Island'),
  Country(IsoCode.CY, 'Cyprus'),
  Country(IsoCode.CZ, 'Czechia'),
  Country(IsoCode.DE, 'Germany'),
  Country(IsoCode.DJ, 'Djibouti'),
  Country(IsoCode.DK, 'Denmark'),
  Country(IsoCode.DM, 'Dominica'),
  Country(IsoCode.DO, 'Dominican Republic'),
  Country(IsoCode.DZ, 'Algeria'),
  Country(IsoCode.EC, 'Ecuador'),
  Country(IsoCode.EE, 'Estonia'),
  Country(IsoCode.EG, 'Egypt'),
  Country(IsoCode.EH, 'Western Sahara'),
  Country(IsoCode.ER, 'Eritrea'),
  Country(IsoCode.ES, 'Spain'),
  Country(IsoCode.ET, 'Ethiopia'),
  Country(IsoCode.FI, 'Finland'),
  Country(IsoCode.FJ, 'Fiji'),
  Country(IsoCode.FK, 'Falkland Islands'),
  Country(IsoCode.FM, 'Micronesia'),
  Country(IsoCode.FO, 'Faroe Islands'),
  Country(IsoCode.FR, 'France'),
  Country(IsoCode.GA, 'Gabon'),
  Country(IsoCode.GB, 'United Kingdom'),
  Country(IsoCode.GD, 'Grenada'),
  Country(IsoCode.GE, 'Georgia'),
  Country(IsoCode.GF, 'French Guiana'),
  Country(IsoCode.GG, 'Guernsey'),
  Country(IsoCode.GH, 'Ghana'),
  Country(IsoCode.GI, 'Gibraltar'),
  Country(IsoCode.GL, 'Greenland'),
  Country(IsoCode.GM, 'Gambia'),
  Country(IsoCode.GN, 'Guinea'),
  Country(IsoCode.GP, 'Guadeloupe'),
  Country(IsoCode.GQ, 'Equatorial Guinea'),
  Country(IsoCode.GR, 'Greece'),
  Country(IsoCode.GT, 'Guatemala'),
  Country(IsoCode.GU, 'Guam'),
  Country(IsoCode.GW, 'Guinea-Bissau'),
  Country(IsoCode.GY, 'Guyana'),
  Country(IsoCode.HK, 'Hong Kong'),
  Country(IsoCode.HN, 'Honduras'),
  Country(IsoCode.HR, 'Croatia'),
  Country(IsoCode.HT, 'Haiti'),
  Country(IsoCode.HU, 'Hungary'),
  Country(IsoCode.ID, 'Indonesia'),
  Country(IsoCode.IE, 'Ireland'),
  Country(IsoCode.IL, 'Israel'),
  Country(IsoCode.IM, 'Isle of Man'),
  Country(IsoCode.IN, 'India'),
  Country(IsoCode.IO, 'British Indian Ocean Territory'),
  Country(IsoCode.IQ, 'Iraq'),
  Country(IsoCode.IR, 'Iran'),
  Country(IsoCode.IS, 'Iceland'),
  Country(IsoCode.IT, 'Italy'),
  Country(IsoCode.JE, 'Jersey'),
  Country(IsoCode.JM, 'Jamaica'),
  Country(IsoCode.JO, 'Jordan'),
  Country(IsoCode.JP, 'Japan'),
  Country(IsoCode.KE, 'Kenya'),
  Country(IsoCode.KG, 'Kyrgyzstan'),
  Country(IsoCode.KH, 'Cambodia'),
  Country(IsoCode.KI, 'Kiribati'),
  Country(IsoCode.KM, 'Comoros'),
  Country(IsoCode.KN, 'Saint Kitts and Nevis'),
  Country(IsoCode.KP, 'North Korea'),
  Country(IsoCode.KR, 'South Korea'),
  Country(IsoCode.KW, 'Kuwait'),
  Country(IsoCode.KY, 'Cayman Islands'),
  Country(IsoCode.KZ, 'Kazakhstan'),
  Country(IsoCode.LA, 'Laos'),
  Country(IsoCode.LB, 'Lebanon'),
  Country(IsoCode.LC, 'Saint Lucia'),
  Country(IsoCode.LI, 'Liechtenstein'),
  Country(IsoCode.LK, 'Sri Lanka'),
  Country(IsoCode.LR, 'Liberia'),
  Country(IsoCode.LS, 'Lesotho'),
  Country(IsoCode.LT, 'Lithuania'),
  Country(IsoCode.LU, 'Luxembourg'),
  Country(IsoCode.LV, 'Latvia'),
  Country(IsoCode.LY, 'Libya'),
  Country(IsoCode.MA, 'Morocco'),
  Country(IsoCode.MC, 'Monaco'),
  Country(IsoCode.MD, 'Moldova'),
  Country(IsoCode.ME, 'Montenegro'),
  Country(IsoCode.MF, 'Saint Martin'),
  Country(IsoCode.MG, 'Madagascar'),
  Country(IsoCode.MH, 'Marshall Islands'),
  Country(IsoCode.MK, 'North Macedonia'),
  Country(IsoCode.ML, 'Mali'),
  Country(IsoCode.MM, 'Myanmar'),
  Country(IsoCode.MN, 'Mongolia'),
  Country(IsoCode.MO, 'Macau'),
  Country(IsoCode.MP, 'Northern Mariana Islands'),
  Country(IsoCode.MQ, 'Martinique'),
  Country(IsoCode.MR, 'Mauritania'),
  Country(IsoCode.MS, 'Montserrat'),
  Country(IsoCode.MT, 'Malta'),
  Country(IsoCode.MU, 'Mauritius'),
  Country(IsoCode.MV, 'Maldives'),
  Country(IsoCode.MW, 'Malawi'),
  Country(IsoCode.MX, 'Mexico'),
  Country(IsoCode.MY, 'Malaysia'),
  Country(IsoCode.MZ, 'Mozambique'),
  Country(IsoCode.NA, 'Namibia'),
  Country(IsoCode.NC, 'New Caledonia'),
  Country(IsoCode.NE, 'Niger'),
  Country(IsoCode.NF, 'Norfolk Island'),
  Country(IsoCode.NG, 'Nigeria'),
  Country(IsoCode.NI, 'Nicaragua'),
  Country(IsoCode.NL, 'Netherlands'),
  Country(IsoCode.NO, 'Norway'),
  Country(IsoCode.NP, 'Nepal'),
  Country(IsoCode.NR, 'Nauru'),
  Country(IsoCode.NU, 'Niue'),
  Country(IsoCode.NZ, 'New Zealand'),
  Country(IsoCode.OM, 'Oman'),
  Country(IsoCode.PA, 'Panama'),
  Country(IsoCode.PE, 'Peru'),
  Country(IsoCode.PF, 'French Polynesia'),
  Country(IsoCode.PG, 'Papua New Guinea'),
  Country(IsoCode.PH, 'Philippines'),
  Country(IsoCode.PK, 'Pakistan'),
  Country(IsoCode.PL, 'Poland'),
  Country(IsoCode.PM, 'Saint Pierre and Miquelon'),
  Country(IsoCode.PR, 'Puerto Rico'),
  Country(IsoCode.PS, 'Palestine'),
  Country(IsoCode.PT, 'Portugal'),
  Country(IsoCode.PW, 'Palau'),
  Country(IsoCode.PY, 'Paraguay'),
  Country(IsoCode.QA, 'Qatar'),
  Country(IsoCode.RE, 'Réunion'),
  Country(IsoCode.RO, 'Romania'),
  Country(IsoCode.RS, 'Serbia'),
  Country(IsoCode.RU, 'Russia'),
  Country(IsoCode.RW, 'Rwanda'),
  Country(IsoCode.SA, 'Saudi Arabia'),
  Country(IsoCode.SB, 'Solomon Islands'),
  Country(IsoCode.SC, 'Seychelles'),
  Country(IsoCode.SD, 'Sudan'),
  Country(IsoCode.SE, 'Sweden'),
  Country(IsoCode.SG, 'Singapore'),
  Country(IsoCode.SH, 'Saint Helena'),
  Country(IsoCode.SI, 'Slovenia'),
  Country(IsoCode.SJ, 'Svalbard and Jan Mayen'),
  Country(IsoCode.SK, 'Slovakia'),
  Country(IsoCode.SL, 'Sierra Leone'),
  Country(IsoCode.SM, 'San Marino'),
  Country(IsoCode.SN, 'Senegal'),
  Country(IsoCode.SO, 'Somalia'),
  Country(IsoCode.SR, 'Suriname'),
  Country(IsoCode.SS, 'South Sudan'),
  Country(IsoCode.ST, 'São Tomé and Príncipe'),
  Country(IsoCode.SV, 'El Salvador'),
  Country(IsoCode.SX, 'Sint Maarten'),
  Country(IsoCode.SY, 'Syria'),
  Country(IsoCode.SZ, 'Eswatini'),
  Country(IsoCode.TA, 'Tristan da Cunha'),
  Country(IsoCode.TC, 'Turks and Caicos Islands'),
  Country(IsoCode.TD, 'Chad'),
  Country(IsoCode.TG, 'Togo'),
  Country(IsoCode.TH, 'Thailand'),
  Country(IsoCode.TJ, 'Tajikistan'),
  Country(IsoCode.TK, 'Tokelau'),
  Country(IsoCode.TL, 'Timor-Leste'),
  Country(IsoCode.TM, 'Turkmenistan'),
  Country(IsoCode.TN, 'Tunisia'),
  Country(IsoCode.TO, 'Tonga'),
  Country(IsoCode.TR, 'Turkey'),
  Country(IsoCode.TT, 'Trinidad and Tobago'),
  Country(IsoCode.TV, 'Tuvalu'),
  Country(IsoCode.TW, 'Taiwan'),
  Country(IsoCode.TZ, 'Tanzania'),
  Country(IsoCode.UA, 'Ukraine'),
  Country(IsoCode.UG, 'Uganda'),
  Country(IsoCode.US, 'United States'),
  Country(IsoCode.UY, 'Uruguay'),
  Country(IsoCode.UZ, 'Uzbekistan'),
  Country(IsoCode.VA, 'Vatican City'),
  Country(IsoCode.VC, 'Saint Vincent and the Grenadines'),
  Country(IsoCode.VE, 'Venezuela'),
  Country(IsoCode.VG, 'British Virgin Islands'),
  Country(IsoCode.VI, 'U.S. Virgin Islands'),
  Country(IsoCode.VN, 'Vietnam'),
  Country(IsoCode.VU, 'Vanuatu'),
  Country(IsoCode.WF, 'Wallis and Futuna'),
  Country(IsoCode.WS, 'Samoa'),
  Country(IsoCode.XK, 'Kosovo'),
  Country(IsoCode.YE, 'Yemen'),
  Country(IsoCode.YT, 'Mayotte'),
  Country(IsoCode.ZA, 'South Africa'),
  Country(IsoCode.ZM, 'Zambia'),
  Country(IsoCode.ZW, 'Zimbabwe'),
];

/// The best default country to preselect: the device's own region, falling
/// back to the US if that isn't one of [kCountries] (e.g. a region code the
/// phone-number library doesn't cover).
Country defaultCountry(String? deviceCountryCode) {
  final upper = deviceCountryCode?.toUpperCase();
  for (final country in kCountries) {
    if (country.isoCode.name == upper) return country;
  }
  return kCountries.firstWhere((c) => c.isoCode == IsoCode.US);
}
